### ISSUE TITLE
cannot load the system

### ISSUE THREAD

**Issue by t-cool** [expez/game-of-life#1]
I tried on my macBook, but it failed to run the program.
Could you give me some advice?

$ cd ~/quicklisp/local-projects/game-of-life-master/
$ ls
game-of-life.asd	patterns
game-of-life.lisp	readme.md
$ cd ~/Desktop/game-of-life-master 
$ ls
game-of-life.asd	patterns
game-of-life.lisp	readme.md
$ sbcl --load game-of-life.lisp all 30
This is SBCL 1.4.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "cl-charms":
  Load 1 ASDF system:
    cl-charms
; Loading "cl-charms"

; file: /Users/noguchihiroki/Desktop/game-of-life-master/game-of-life.lisp
; in: DEFUN UPDATE-BOARD
;     (GAME-OF-LIFE::GET-CELL-UPDATE GAME-OF-LIFE::X GAME-OF-LIFE::Y)
; 
; caught STYLE-WARNING:
;   undefined function: GET-CELL-UPDATE

;     (GAME-OF-LIFE::PERFORM-UPDATES GAME-OF-LIFE::UPDATES)
; 
; caught STYLE-WARNING:
;   undefined function: PERFORM-UPDATES
; 
; compilation unit finished
;   Undefined functions:
;     GET-CELL-UPDATE PERFORM-UPDATES
;   caught 2 STYLE-WARNING conditions

; in: DEFUN GET-CELL-UPDATE
;     #'GAME-OF-LIFE::BIRTH
; 
; caught STYLE-WARNING:
;   undefined function: BIRTH

;     #'GAME-OF-LIFE::KILL
; 
; caught STYLE-WARNING:
;   undefined function: KILL

;     (GAME-OF-LIFE::NUM-NEIGHBORS GAME-OF-LIFE::X GAME-OF-LIFE::Y)
; 
; caught STYLE-WARNING:
;   undefined function: NUM-NEIGHBORS
; 
; compilation unit finished
;   Undefined functions:
;     BIRTH KILL NUM-NEIGHBORS
;   caught 3 STYLE-WARNING conditions

; in: DEFUN NUM-NEIGHBORS
;     (GAME-OF-LIFE::NEIGHBOR GAME-OF-LIFE::X GAME-OF-LIFE::Y GAME-OF-LIFE::DIR)
; 
; caught STYLE-WARNING:
;   undefined function: NEIGHBOR
; 
; compilation unit finished
;   Undefined function:
;     NEIGHBOR
;   caught 1 STYLE-WARNING condition

; in: DEFUN RUN
;     (GAME-OF-LIFE::EXIT-LIFE)
; 
; caught STYLE-WARNING:
;   undefined function: EXIT-LIFE

;     (GAME-OF-LIFE::GET-BAG-OF-PATTERNS)
; 
; caught STYLE-WARNING:
;   undefined function: GET-BAG-OF-PATTERNS

;     (GAME-OF-LIFE::GET-PATTERN-NAME-FROM-ARGV)
; 
; caught STYLE-WARNING:
;   undefined function: GET-PATTERN-NAME-FROM-ARGV

;     (GAME-OF-LIFE::INIT-CURSES)
; 
; caught STYLE-WARNING:
;   undefined function: INIT-CURSES

;     (MAPC #'GAME-OF-LIFE::RUN-PATTERN (GAME-OF-LIFE::GET-BAG-OF-PATTERNS))
; --> LET LET SB-INT:DO-ANONYMOUS BLOCK LET TAGBODY TAGBODY FUNCALL 
; ==>
;   (SB-C::%FUNCALL #'GAME-OF-LIFE::RUN-PATTERN (CAR #:G1))
; 
; caught STYLE-WARNING:
;   undefined function: RUN-PATTERN

;     (GAME-OF-LIFE::SET-NUM-TIMESTEPS)
; 
; caught STYLE-WARNING:
;   undefined function: SET-NUM-TIMESTEPS
; 
; compilation unit finished
;   Undefined functions:
;     EXIT-LIFE GET-BAG-OF-PATTERNS GET-PATTERN-NAME-FROM-ARGV INIT-CURSES RUN-PATTERN SET-NUM-TIMESTEPS
;   caught 6 STYLE-WARNING conditions

; in: DEFUN RUN-PATTERN
;     (GAME-OF-LIFE::GAME-LOOP)
; 
; caught STYLE-WARNING:
;   undefined function: GAME-LOOP

;     (GAME-OF-LIFE::POPULATE-BOARD GAME-OF-LIFE::PATTERN)
; 
; caught STYLE-WARNING:
;   undefined function: POPULATE-BOARD

;     (GAME-OF-LIFE::READ-PATTERN-FROM-FILE GAME-OF-LIFE::NAME)
; 
; caught STYLE-WARNING:
;   undefined function: READ-PATTERN-FROM-FILE

;     (GAME-OF-LIFE::RESET-BOARD)
; 
; caught STYLE-WARNING:
;   undefined function: RESET-BOARD
; 
; compilation unit finished
;   Undefined functions:
;     GAME-LOOP POPULATE-BOARD READ-PATTERN-FROM-FILE RESET-BOARD
;   caught 4 STYLE-WARNING conditions

; in: DEFUN INIT-CURSES
;     (GAME-OF-LIFE::KEYPAD GAME-OF-LIFE::*STDSCR* GAME-OF-LIFE::TRUE)
; 
; caught WARNING:
;   undefined variable: *STDSCR*

;     (GAME-OF-LIFE::CURS-SET 0)
; 
; caught STYLE-WARNING:
;   undefined function: CURS-SET

;     (GAME-OF-LIFE::INITSCR)
; 
; caught STYLE-WARNING:
;   undefined function: INITSCR

;     (GAME-OF-LIFE::KEYPAD GAME-OF-LIFE::*STDSCR* GAME-OF-LIFE::TRUE)
; 
; caught STYLE-WARNING:
;   undefined function: KEYPAD

;     (GAME-OF-LIFE::NOECHO)
; 
; caught STYLE-WARNING:
;   undefined function: NOECHO

;     (GAME-OF-LIFE::RAW)
; 
; caught STYLE-WARNING:
;   undefined function: RAW

;     (GAME-OF-LIFE::KEYPAD GAME-OF-LIFE::*STDSCR* GAME-OF-LIFE::TRUE)
; 
; caught WARNING:
;   undefined variable: TRUE
; 
; compilation unit finished
;   Undefined functions:
;     CURS-SET INITSCR KEYPAD NOECHO RAW
;   Undefined variables:
;     *STDSCR* TRUE
;   caught 2 WARNING conditions
;   caught 5 STYLE-WARNING conditions

; in: DEFUN GAME-LOOP
;     (GAME-OF-LIFE::DRAW-BOARD)
; 
; caught STYLE-WARNING:
;   undefined function: DRAW-BOARD
; 
; compilation unit finished
;   Undefined function:
;     DRAW-BOARD
;   caught 1 STYLE-WARNING condition

; in: DEFUN DRAW-BOARD
;     (GAME-OF-LIFE::DRAW GAME-OF-LIFE::X GAME-OF-LIFE::Y (CHAR-CODE #\*))
; 
; caught STYLE-WARNING:
;   undefined function: DRAW

;     (GAME-OF-LIFE::REFRESH)
; 
; caught STYLE-WARNING:
;   undefined function: REFRESH
; 
; compilation unit finished
;   Undefined functions:
;     DRAW REFRESH
;   caught 2 STYLE-WARNING conditions

; in: DEFUN DRAW
;     (GAME-OF-LIFE::MVADDCH GAME-OF-LIFE::X GAME-OF-LIFE::Y GAME-OF-LIFE::CH)
; 
; caught STYLE-WARNING:
;   undefined function: MVADDCH
; 
; compilation unit finished
;   Undefined function:
;     MVADDCH
;   caught 1 STYLE-WARNING condition

; in: DEFUN EXIT-LIFE
;     (GAME-OF-LIFE::ENDWIN)
; 
; caught STYLE-WARNING:
;   undefined function: ENDWIN
; 
; compilation unit finished
;   Undefined function:
;     ENDWIN
;   caught 1 STYLE-WARNING condition

; in: DEFUN GET-PATTERN-NAME-FROM-ARGV
;     (GAME-OF-LIFE::SANITIZE-NAME (SECOND GAME-OF-LIFE::ARGS))
; 
; caught STYLE-WARNING:
;   undefined function: SANITIZE-NAME
; 
; compilation unit finished
;   Undefined function:
;     SANITIZE-NAME
;   caught 1 STYLE-WARNING condition

; in: DEFUN GET-NUM-TIMESTEPS-FROM-ARGV
;     (GAME-OF-LIFE::SAFELY-READ-FROM-STRING (THIRD GAME-OF-LIFE::ARGS))
; 
; caught STYLE-WARNING:
;   undefined function: SAFELY-READ-FROM-STRING
; 
; compilation unit finished
;   Undefined function:
;     SAFELY-READ-FROM-STRING
;   caught 1 STYLE-WARNING condition

; in: DEFUN READ-PATTERN-FROM-FILE
;     (GAME-OF-LIFE::SANITIZE-NAME GAME-OF-LIFE::LINE)
; 
; caught STYLE-WARNING:
;   undefined function: SANITIZE-NAME

;     (GAME-OF-LIFE::SANITIZE-PATTERN (NREVERSE GAME-OF-LIFE::PATTERN))
; 
; caught STYLE-WARNING:
;   undefined function: SANITIZE-PATTERN
; 
; compilation unit finished
;   Undefined functions:
;     SANITIZE-NAME SANITIZE-PATTERN
;   caught 2 STYLE-WARNING conditions
While evaluating the form starting at line 178, column 0
  of #P"/Users/noguchihiroki/Desktop/game-of-life-master/game-of-life.lisp":

debugger invoked on a UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {1001937063}>:
  The function GAME-OF-LIFE::INITSCR is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE      ] Retry calling INITSCR.
  1: [USE-VALUE     ] Call specified function.
  2: [RETURN-VALUE  ] Return specified values.
  3: [RETURN-NOTHING] Return zero values.
  4: [RETRY         ] Retry EVAL of current toplevel form.
  5:                  Ignore error and continue loading file "/Users/noguchihiroki/Desktop/game-of-life-master/game-of-life.lisp".
  6: [ABORT         ] Abort loading file "/Users/noguchihiroki/Desktop/game-of-life-master/game-of-life.lisp".
  7:                  Ignore runtime option --load "game-of-life.lisp".
  8:                  Skip rest of --eval and --load options.
  9:                  Skip to toplevel READ/EVAL/PRINT loop.
 10: [EXIT          ] Exit SBCL (calling #'EXIT, killing the process).

("undefined function")
0] 0

**Comment by expez** [comment]
Sorry this isn't working anymore.

I wrote this as a fun exercise while learning common lisp, but I'm not really into that anymore, so I can't offer any meaningful help here.

**Comment by t-cool** [comment]
Thank you for your reply. I'll try to fix it by myself:)
